#!/usr/bin/env bash

docker buildx create --use --platform linux/arm64,linux/amd64 --driver docker-container 
docker build --platform linux/arm64,linux/amd64 --push -f $DOCKERFILE_PATH -t $IMAGE_NAME .

