name: release-container-image

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch: # Manual Trigger
    inputs:
      docker_tag:
        description: 'Docker tag to use'
        required: true
        default: 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get the tag
        run: |
          TAG=${{ github.ref_name }}
          if [[ $TAG == "master" ]]; then
            TAG=latest
          fi
          MANUAL_WORKFLOW_TAG=${{ inputs.docker_tag }}
          if [[ $MANUAL_WORKFLOW_TAG != "" ]]; then
            TAG=${{ inputs.docker_tag }}
          fi
          echo "Using tag $TAG"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/datastax/pulsar-admin-console:$TAG
